/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as MacrosRouteImport } from './routes/macros'
import { Route as GymRouteImport } from './routes/gym'
import { Route as DeepWorkRouteImport } from './routes/deep-work'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersMemberIdRouteImport } from './routes/members.$memberId'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'

const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosRoute = MacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepWorkRoute = DeepWorkRouteImport.update({
  id: '/deep-work',
  path: '/deep-work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
  '/macros': typeof MacrosRoute
  '/sleep': typeof SleepRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
  '/macros': typeof MacrosRoute
  '/sleep': typeof SleepRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
  '/macros': typeof MacrosRoute
  '/sleep': typeof SleepRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/deep-work'
    | '/gym'
    | '/macros'
    | '/sleep'
    | '/members/$memberId'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/deep-work'
    | '/gym'
    | '/macros'
    | '/sleep'
    | '/members/$memberId'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/deep-work'
    | '/gym'
    | '/macros'
    | '/sleep'
    | '/members/$memberId'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DeepWorkRoute: typeof DeepWorkRoute
  GymRoute: typeof GymRoute
  MacrosRoute: typeof MacrosRoute
  SleepRoute: typeof SleepRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros': {
      id: '/macros'
      path: '/macros'
      fullPath: '/macros'
      preLoaderRoute: typeof MacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-work': {
      id: '/deep-work'
      path: '/deep-work'
      fullPath: '/deep-work'
      preLoaderRoute: typeof DeepWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DeepWorkRoute: DeepWorkRoute,
  GymRoute: GymRoute,
  MacrosRoute: MacrosRoute,
  SleepRoute: SleepRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
