/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as MacrosRouteImport } from './routes/macros'
import { Route as GymRouteImport } from './routes/gym'
import { Route as DeepWorkRouteImport } from './routes/deep-work'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberMemberIdRouteImport } from './routes/member.$memberId'

const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosRoute = MacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepWorkRoute = DeepWorkRouteImport.update({
  id: '/deep-work',
  path: '/deep-work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberMemberIdRoute = MemberMemberIdRouteImport.update({
  id: '/member/$memberId',
  path: '/member/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
  '/macros': typeof MacrosRoute
  '/sleep': typeof SleepRoute
  '/member/$memberId': typeof MemberMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
  '/macros': typeof MacrosRoute
  '/sleep': typeof SleepRoute
  '/member/$memberId': typeof MemberMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
  '/macros': typeof MacrosRoute
  '/sleep': typeof SleepRoute
  '/member/$memberId': typeof MemberMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/deep-work'
    | '/gym'
    | '/macros'
    | '/sleep'
    | '/member/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/deep-work'
    | '/gym'
    | '/macros'
    | '/sleep'
    | '/member/$memberId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/deep-work'
    | '/gym'
    | '/macros'
    | '/sleep'
    | '/member/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DeepWorkRoute: typeof DeepWorkRoute
  GymRoute: typeof GymRoute
  MacrosRoute: typeof MacrosRoute
  SleepRoute: typeof SleepRoute
  MemberMemberIdRoute: typeof MemberMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros': {
      id: '/macros'
      path: '/macros'
      fullPath: '/macros'
      preLoaderRoute: typeof MacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-work': {
      id: '/deep-work'
      path: '/deep-work'
      fullPath: '/deep-work'
      preLoaderRoute: typeof DeepWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/$memberId': {
      id: '/member/$memberId'
      path: '/member/$memberId'
      fullPath: '/member/$memberId'
      preLoaderRoute: typeof MemberMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DeepWorkRoute: DeepWorkRoute,
  GymRoute: GymRoute,
  MacrosRoute: MacrosRoute,
  SleepRoute: SleepRoute,
  MemberMemberIdRoute: MemberMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
