/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GymRouteImport } from './routes/gym'
import { Route as DeepWorkRouteImport } from './routes/deep-work'
import { Route as IndexRouteImport } from './routes/index'

const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepWorkRoute = DeepWorkRouteImport.update({
  id: '/deep-work',
  path: '/deep-work',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deep-work': typeof DeepWorkRoute
  '/gym': typeof GymRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deep-work' | '/gym'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deep-work' | '/gym'
  id: '__root__' | '/' | '/deep-work' | '/gym'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeepWorkRoute: typeof DeepWorkRoute
  GymRoute: typeof GymRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-work': {
      id: '/deep-work'
      path: '/deep-work'
      fullPath: '/deep-work'
      preLoaderRoute: typeof DeepWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeepWorkRoute: DeepWorkRoute,
  GymRoute: GymRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
